AllCops:
  Include:
    - Cheffile
    - Gemfile
    - Rakefile
  Exclude:
   - cookbooks/**/*
   - tmp/**/*

SpaceBeforeFirstArg:
  Enabled: false # Useful for more readable alignment of method call args

LineLength:
  Max: 120

BlockDelimiters:
  Enabled: false # For multi-line expect { ... }.to blah { ... }
